name: devals
description: CLI for managing dash-evals - create samples, run evaluations, and view results.
version: 0.0.1
publish_to: none
resolution: workspace

executables:
  devals:

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  dotenv: ^4.2.0
  gcloud: ^0.9.0
  glob: ^2.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0
  howdy:
    git: 
      url: https://github.com/ericwindmill/howdy.git
      path: packages/howdy-cli
  eval_config:
    path: ../eval_config
  path: ^1.9.0
  yaml: ^3.1.0
  yaml_edit: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: any
